
(function(){
'use strict';
const GPS_MIN_MS=60*1000;let auth,db,user=null,rider=null,orders=[],filter='active',lastGpsAt=0,recaptcha,confirmationResult;
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
function clean(v){return String(v??'').trim()} function phone10(v){let d=clean(v).replace(/\D/g,'');return d.length>10?d.slice(-10):d} function now(){return firebase.firestore.FieldValue.serverTimestamp()} function esc(v){return clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))} function money(v){return '₹'+Math.round(Number(v||0))}
function status(o){return clean(o.adminStatus||o.orderStatus||o.deliveryStatus||o.riderStatus||o.status||'confirmed').toLowerCase().replace(/[\s-]+/g,'_')}
function active(o){return !['delivered','completed','cancelled','canceled'].includes(status(o))}
function setNotice(msg){const n=$('#notice');n.hidden=!msg;n.textContent=msg||''}
function init(){if(!window.firebase||!window.TIFFIN_FIREBASE_CONFIG){setNotice('Firebase config missing');return}firebase.initializeApp(window.TIFFIN_FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();bind();auth.onAuthStateChanged(onAuth)}
function bind(){ $('#sendOtpBtn').onclick=sendOtp; $('#verifyOtpBtn').onclick=verifyOtp; $('#backToPhoneBtn').onclick=()=>showPhone(); $('#saveNameBtn').onclick=saveName; $('#logoutBtn').onclick=()=>auth.signOut(); $('#refreshBtn').onclick=()=>location.reload(); $('#onlineBtn').onclick=toggleOnline; $('#updateGpsBtn').onclick=()=>syncGps(true); $$('.chip').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('.chip').forEach(x=>x.classList.toggle('active',x===b));renderOrders()}); $('#phoneInput').addEventListener('input',e=>e.target.value=phone10(e.target.value));}
async function sendOtp(){let p=phone10($('#phoneInput').value);if(p.length!==10){setNotice('Enter valid 10 digit phone');return}setNotice('Sending OTP...');try{if(recaptcha)recaptcha.clear();recaptcha=new firebase.auth.RecaptchaVerifier('recaptcha-container',{size:'invisible'});confirmationResult=await auth.signInWithPhoneNumber('+91'+p,recaptcha);localStorage.setItem('rider_pending_phone',p);showOtp();setNotice('OTP sent to +91 '+p)}catch(e){setNotice(e.message)}}
async function verifyOtp(){let otp=clean($('#otpInput').value);if(otp.length!==6){setNotice('Enter 6 digit OTP');return}try{let res=await confirmationResult.confirm(otp);await ensureRider(res.user); }catch(e){setNotice(e.message)}}
async function onAuth(u){user=u;if(!u){$('#loginCard').hidden=false;$('#riderPanel').hidden=true;$('#connectionText').textContent='Logged out';return}await ensureRider(u)}
async function ensureRider(u){let phone=phone10(u.phoneNumber||localStorage.getItem('rider_pending_phone'));let id=phone||u.uid;let ref=db.collection('riders').doc(id);let snap=await ref.get();if(!snap.exists||!clean(snap.data().name)){localStorage.setItem('rider_phone',phone);localStorage.setItem('rider_doc_id',id);showName();return}rider={id,...snap.data(),phone};localStorage.setItem('rider_phone',phone);localStorage.setItem('rider_doc_id',id);await ref.set({uid:u.uid,phone,updatedAt:now()},{merge:true});startApp()}
function showPhone(){$('#phoneScreen').hidden=false;$('#otpScreen').hidden=true;$('#nameScreen').hidden=true} function showOtp(){$('#phoneScreen').hidden=true;$('#otpScreen').hidden=false;$('#nameScreen').hidden=true;setTimeout(()=>$('#otpInput').focus(),80)} function showName(){$('#phoneScreen').hidden=true;$('#otpScreen').hidden=true;$('#nameScreen').hidden=false;setTimeout(()=>$('#riderNameInput').focus(),80)}
async function saveName(){let name=clean($('#riderNameInput').value);if(name.length<2){setNotice('Enter your name');return}let phone=phone10(localStorage.getItem('rider_phone')||user.phoneNumber), id=phone||user.uid;await db.collection('riders').doc(id).set({uid:user.uid,name,phone,online:false,createdAt:now(),updatedAt:now()},{merge:true});rider={id,name,phone,online:false};startApp()}
function startApp(){ $('#loginCard').hidden=true;$('#riderPanel').hidden=false;$('#riderNameText').textContent=rider.name||'Rider';$('#riderPhoneText').textContent='+91 '+(rider.phone||'');$('#riderInitial').textContent=(rider.name||'R')[0].toUpperCase();$('#connectionText').textContent='Rider live panel';listen();syncGps(false)}
function listen(){db.collection('riders').doc(rider.id).onSnapshot(s=>{rider={id:rider.id,...(s.data()||{})};$('#onlineBtn').textContent=rider.online?'Go offline':'Go online';$('#onlineBtn').classList.toggle('primary',!rider.online)});db.collection('orders').orderBy('createdAt','desc').limit(80).onSnapshot(s=>{orders=s.docs.map(d=>({id:d.id,...d.data()}));renderOrders()})}
function filtered(){return orders.filter(o=>{let s=status(o), mine=(o.assignedRiderId===rider.id||o.riderId===rider.id||phone10(o.assignedRiderPhone||o.riderPhone)===rider.phone); if(filter==='past')return mine&&['delivered','completed'].includes(s); if(filter==='available')return active(o)&&['ready','prepared'].includes(s)&&!o.assignedRiderId&&!o.riderId; return mine&&active(o)})}
function renderOrders(){let list=$('#ordersList'),data=filtered();if(!data.length){list.innerHTML='<div class="empty">No orders here.</div>';return}list.innerHTML=data.map(card).join('');list.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.id,b.dataset.action))}
function itemsHtml(items){items=Array.isArray(items)?items:[];return items.map(i=>`<span class="item-chip">${esc(i.name||i.title||'Item')} × ${esc(i.qty||i.quantity||1)}</span>`).join('')||'<span class="item-chip">Items unavailable</span>'}
function card(o){let s=status(o),addr=o.deliveryAddress||o.address||o.deliveryLocation?.fullAddress||'',cust=o.customerName||o.customer?.name||'Customer',ph=o.customerPhone||o.customer?.phone||'';return `<article class="order-card"><div class="order-head"><div><div class="order-id">#${esc(o.id)}</div><span class="badge green">${esc(label(s))}</span></div><b>${money(o.total||o.totalPaid||o.totals?.total)}</b></div><div class="items">${itemsHtml(o.items)}</div><div class="kv"><span>Customer</span><b>${esc(cust)} ${ph?`· ${esc(ph)}`:''}</b><span>Address</span><span>${esc(addr)}</span><span>Phone</span><span>${ph?`<a href="tel:${esc(ph)}">Call ${esc(ph)}</a>`:'-'}</span></div><div class="actions">${actions(o,s)}</div></article>`}
function actions(o,s){if(filter==='available')return `<button class="btn primary small" data-action="accept" data-id="${esc(o.id)}">Accept delivery</button>`;let a=[];if(['rider_assigned','assigned','ready','prepared'].includes(s))a.push(`<button class="btn primary small" data-action="pickup" data-id="${esc(o.id)}">Picked up</button>`);if(['picked_up','out_for_delivery','on_the_way'].includes(s))a.push(`<button class="btn soft small" data-action="reached" data-id="${esc(o.id)}">Reached location</button>`);if(['reached_location','reached','arrived','picked_up','out_for_delivery','on_the_way'].includes(s))a.push(`<button class="btn primary small" data-action="delivered" data-id="${esc(o.id)}">Delivered</button>`);return a.join('')||'<span class="muted">Waiting for admin</span>'}
function label(s){return ({ready:'Ready',prepared:'Ready',rider_assigned:'Assigned',assigned:'Assigned',picked_up:'Out for delivery',out_for_delivery:'Out for delivery',reached_location:'Reached',reached:'Reached',delivered:'Delivered'}[s]||s.replace(/_/g,' '))}
function byId(id){return orders.find(o=>o.id===id)||{id}}
async function patchOrder(o,patch){patch={...patch,updatedAt:now()};await db.collection('orders').doc(o.id).set(patch,{merge:true});if(o.customerId)await db.collection('customers').doc(o.customerId).collection('orders').doc(o.id).set(patch,{merge:true})}
async function act(id,a){let o=byId(id);if(a==='accept'){await patchOrder(o,{status:'rider_assigned',orderStatus:'rider_assigned',adminStatus:'rider_assigned',assignedRiderId:rider.id,riderId:rider.id,assignedRiderName:rider.name,assignedRiderPhone:rider.phone,riderName:rider.name,riderPhone:rider.phone,assignedAt:now()});return}if(a==='pickup'){let loc=await syncGps(true);await patchOrder(o,{status:'out_for_delivery',orderStatus:'out_for_delivery',adminStatus:'out_for_delivery',riderStatus:'picked_up',pickedUpAt:now(),riderLocation:loc||undefined,riderName:rider.name,riderPhone:rider.phone,assignedRiderName:rider.name,assignedRiderPhone:rider.phone})}if(a==='reached'){let loc=await syncGps(true);await patchOrder(o,{status:'reached_location',orderStatus:'reached_location',adminStatus:'reached_location',riderStatus:'reached_location',reachedAt:now(),riderLocation:loc||undefined})}if(a==='delivered'){let loc=await syncGps(true);await patchOrder(o,{status:'delivered',orderStatus:'delivered',adminStatus:'delivered',riderStatus:'delivered',deliveredAt:now(),completedAt:now(),riderLocation:loc||undefined})}}
async function toggleOnline(){await db.collection('riders').doc(rider.id).set({online:!rider.online,updatedAt:now()},{merge:true});if(!rider.online)syncGps(true)}
function getPosition(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,at:new Date().toISOString()}),()=>resolve(null),{enableHighAccuracy:true,timeout:12000,maximumAge:30000})})}
async function syncGps(force){if(!force&&Date.now()-lastGpsAt<GPS_MIN_MS)return null;lastGpsAt=Date.now();$('#gpsText').textContent='Updating GPS...';let loc=await getPosition();if(!loc){$('#gpsText').textContent='GPS permission needed';return null}await db.collection('riders').doc(rider.id).set({location:loc,online:true,lastLocationAt:now(),updatedAt:now()},{merge:true});let mine=orders.filter(o=>(o.assignedRiderId===rider.id||o.riderId===rider.id)&&['picked_up','out_for_delivery','on_the_way','reached_location'].includes(status(o)));for(const o of mine) await patchOrder(o,{riderLocation:loc,liveRiderLocation:loc});$('#gpsText').textContent=`GPS synced ${new Date().toLocaleTimeString()}`;return loc}
document.addEventListener('DOMContentLoaded',init);
})();
